BODY = [
    "Hair\n\nCabello",
    "Ayes\n\nOjos",
    "Nose\n\nNariz",
    "Forehead\n\nFrente",
    "Ear\n\nOreja",
    "Tooth/Teeth\n\nDiente/Dientes",
    "Mouth\n\nBoca",
    "Neck\n\nCuello",
    "Chest\n\nPecho",
    "Shoulders\n\nHombros",
    "Elbows\n\nCodos",
    "Arms\n\nBrazos",
    "Hands\n\nManos",
    "Fingers\n\nDedos",
    "Stomach\n\nEstomago",
    "Pierna\n\nLegs",
    "Foot/Feet\n\nPie/Pies",
    "Ankles\n\nTobillos",
    "Knees\n\nRodillas",
]

