W_SENTENCES = [
    "*Anyway*, if we want, we can do that...\n\n*De todos modos*, si queremos, podemos hacerlo...",
    "My *apologies*, i was late because the trafic was hard.\n\nMis *disculpas*, llegué tarde porque el tráfico era duro.",
    "Sorry but i've got to go away *due* my engagement.\n\nLo siento pero tengo que irme *debido* mi compromiso.",
    "If you really want to learn English, you must *engage* to study.\n\nSi realmente quieres aprender inglés, debes *comprometerte* a estudiar.",
    "The *facts* was horrible...\n\nLos *hechos* fueron horribles...",
    "The dog goes on *forward* to its objective.\n\nEl perro sigue *adelante hacia su objetivo.",
    "If your objective is will be the best, go on *forward*.\n\nSi tu objetivo es ser el mejor, sigue *[hacia] adelante*.",
    "That was my plan, *however\nevertheless*, it didn't work out.\n\nEse era mi plan, *sin embargo\no obstante*, no funcionó.",
    "*In fact*, i don't like the fry chicken.\n\n*De hecho*, no me gusta el pollo frito.",
    "Oh babe, don't leave me please!\n\n¡Oh nena, no me dejes por favor!",
    "I want a hamburger and *moreover*, i want a soda.\n\nQuiero una hamburguesa, y *además*, quiero un refresco.",
    "I hate the city, it's quite *noise*!\n\nOdio la ciudad, ¡es bastante *ruidosa*!",
    "For the next week, you must to make a biology cells overview...\n\nPara la próxima semana, deben hacer un resumen de las células de biología..",
    "Don't *rush* yourself, you've got three weeks to do that.\n\nNo te *apresures*, tienes tres semanas para hacerlo.",
    "And finally, here's my English study *schedule*...\n\nY finalmente, aquí está mi *horario* de estudio de inglés...",
    "I hate the British *slang*, i don't understand it!\n\nOdio la *jerga* británica, ¡no la entiendo!",
    "Whoa! that was *slightly* intense...\n\n¡Whoa! Eso fue *ligeramente* intenso...",
    "hey! go on straightforward to the success bro.\n\n¡Hey! ve directo al éxito hermano.",
    "If you want to arrive the town, pass *through* the tunnel.\n\nSi quieres llegar a la ciudad, pasa *en medio* del túnel.",
    "Wait for me, i'm going to *throwaway* the garbage.\n\nEsperame, voy a *tirar\desechar* la basura.",
    "Today we're going to train our whole personal.\n\nHoy vamos a *capacitar\entrenar* todo nuestro personal.",
    "This is the new jacket model, it's the last on *trends*.\n\nEste es el nuevo modelo de chaqueta, es el último en *tendencia[s]*.",
    "Hey bro, i'm feeling *uncomfortable* here.\n\nHey hermano, me siento *incómodo* aquí.",
    "Now, the university is becoming *useless*.\n\nAhora, la universidad se está volviendo *inútil*.",
    "Her feelings are *weak*...\n\nSus sentimientos son débiles...",
]
